# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '6.0.1'
  pod 'Google-Maps-iOS-Utils', '~> 4.1.0'
  pod 'Kingfisher', '~> 7.0'

end
